// Code generated by goctl. DO NOT EDIT.
// Source: pay.proto

package pay

import (
	"context"

	"golang-senior-learn/chapter3/mall/pay/pay/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PayCode    = pb.PayCode
	PayCodeReq = pb.PayCodeReq
	PayCodeRes = pb.PayCodeRes
	Resp       = pb.Resp

	Pay interface {
		GetPayCode(ctx context.Context, in *PayCodeReq, opts ...grpc.CallOption) (*PayCodeRes, error)
	}

	defaultPay struct {
		cli zrpc.Client
	}
)

func NewPay(cli zrpc.Client) Pay {
	return &defaultPay{
		cli: cli,
	}
}

func (m *defaultPay) GetPayCode(ctx context.Context, in *PayCodeReq, opts ...grpc.CallOption) (*PayCodeRes, error) {
	client := pb.NewPayClient(m.cli.Conn())
	return client.GetPayCode(ctx, in, opts...)
}
