// Code generated by goctl. DO NOT EDIT.
package types

type CreateOrderReq struct {
	PayMethod string  `json:"payMethod,options=alipay|wechat"` //支付方式，alipay, wechat
	Amount    float32 `json:"amount"`                          //金额
	Month     int32   `json:"month"`                           //月数
}

type Order struct {
	OrderId     int64  `json:"orderId"`     //订单id
	PayUrl      string `json:"payUrl"`      //支付链接
	OrderStatus string `json:"orderStatus"` //订单状态
	PayMethod   string `json:"payMethod"`   //支付方式
	ExpireAt    string `json:"expireAt"`    //过期时间
}

type Resp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
	Data Order  `json:"data"`
}
