// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package profile

import (
	"user-admin/api/profile"
)

type ControllerV1 struct{}

func NewV1() profile.IProfileV1 {
	return &ControllerV1{}
}
