// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: pay.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayStatus int32

const (
	PayStatus_PENDING PayStatus = 0
	PayStatus_SUCCESS PayStatus = 1
	PayStatus_FAIL    PayStatus = 2
)

// Enum value maps for PayStatus.
var (
	PayStatus_name = map[int32]string{
		0: "PENDING",
		1: "SUCCESS",
		2: "FAIL",
	}
	PayStatus_value = map[string]int32{
		"PENDING": 0,
		"SUCCESS": 1,
		"FAIL":    2,
	}
)

func (x PayStatus) Enum() *PayStatus {
	p := new(PayStatus)
	*p = x
	return p
}

func (x PayStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pay_proto_enumTypes[0].Descriptor()
}

func (PayStatus) Type() protoreflect.EnumType {
	return &file_pay_proto_enumTypes[0]
}

func (x PayStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayStatus.Descriptor instead.
func (PayStatus) EnumDescriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{0}
}

type PayPlatform int32

const (
	PayPlatform___UNKNOWN__ PayPlatform = 0
	PayPlatform_ALIPAY      PayPlatform = 1
	PayPlatform_WECHAT      PayPlatform = 2
)

// Enum value maps for PayPlatform.
var (
	PayPlatform_name = map[int32]string{
		0: "__UNKNOWN__",
		1: "ALIPAY",
		2: "WECHAT",
	}
	PayPlatform_value = map[string]int32{
		"__UNKNOWN__": 0,
		"ALIPAY":      1,
		"WECHAT":      2,
	}
)

func (x PayPlatform) Enum() *PayPlatform {
	p := new(PayPlatform)
	*p = x
	return p
}

func (x PayPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_pay_proto_enumTypes[1].Descriptor()
}

func (PayPlatform) Type() protoreflect.EnumType {
	return &file_pay_proto_enumTypes[1]
}

func (x PayPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayPlatform.Descriptor instead.
func (PayPlatform) EnumDescriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{1}
}

type PayCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64       `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderId  int64       `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Platform PayPlatform `protobuf:"varint,3,opt,name=platform,proto3,enum=pay.pb.PayPlatform" json:"platform,omitempty"`
	Amount   float32     `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Subject  string      `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *PayCodeReq) Reset() {
	*x = PayCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCodeReq) ProtoMessage() {}

func (x *PayCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCodeReq.ProtoReflect.Descriptor instead.
func (*PayCodeReq) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{0}
}

func (x *PayCodeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayCodeReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PayCodeReq) GetPlatform() PayPlatform {
	if x != nil {
		return x.Platform
	}
	return PayPlatform___UNKNOWN__
}

func (x *PayCodeReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PayCodeReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{1}
}

func (x *Resp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Resp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PayCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp    `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Data *PayCode `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PayCodeRes) Reset() {
	*x = PayCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCodeRes) ProtoMessage() {}

func (x *PayCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCodeRes.ProtoReflect.Descriptor instead.
func (*PayCodeRes) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{2}
}

func (x *PayCodeRes) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *PayCodeRes) GetData() *PayCode {
	if x != nil {
		return x.Data
	}
	return nil
}

type PayCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId  int64     `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	PayUrl   string    `protobuf:"bytes,2,opt,name=payUrl,proto3" json:"payUrl,omitempty"`
	Status   PayStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pay.pb.PayStatus" json:"status,omitempty"`
	ExpireAt string    `protobuf:"bytes,4,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
}

func (x *PayCode) Reset() {
	*x = PayCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCode) ProtoMessage() {}

func (x *PayCode) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCode.ProtoReflect.Descriptor instead.
func (*PayCode) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{3}
}

func (x *PayCode) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PayCode) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *PayCode) GetStatus() PayStatus {
	if x != nil {
		return x.Status
	}
	return PayStatus_PENDING
}

func (x *PayCode) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

var File_pay_proto protoreflect.FileDescriptor

var file_pay_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x61, 0x79,
	0x2e, 0x70, 0x62, 0x22, 0xa1, 0x01, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x61, 0x79, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x2c, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x53, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x82, 0x01, 0x0a, 0x07, 0x50,
	0x61, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x2a,
	0x2f, 0x0a, 0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02,
	0x2a, 0x36, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x0f, 0x0a, 0x0b, 0x5f, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x5f, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x4c, 0x49, 0x50, 0x41, 0x59, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x57, 0x45, 0x43, 0x48, 0x41, 0x54, 0x10, 0x02, 0x32, 0x3b, 0x0a, 0x03, 0x50, 0x61, 0x79, 0x12,
	0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e,
	0x70, 0x61, 0x79, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x12, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x61, 0x79, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pay_proto_rawDescOnce sync.Once
	file_pay_proto_rawDescData = file_pay_proto_rawDesc
)

func file_pay_proto_rawDescGZIP() []byte {
	file_pay_proto_rawDescOnce.Do(func() {
		file_pay_proto_rawDescData = protoimpl.X.CompressGZIP(file_pay_proto_rawDescData)
	})
	return file_pay_proto_rawDescData
}

var file_pay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pay_proto_goTypes = []any{
	(PayStatus)(0),     // 0: pay.pb.PayStatus
	(PayPlatform)(0),   // 1: pay.pb.PayPlatform
	(*PayCodeReq)(nil), // 2: pay.pb.PayCodeReq
	(*Resp)(nil),       // 3: pay.pb.Resp
	(*PayCodeRes)(nil), // 4: pay.pb.PayCodeRes
	(*PayCode)(nil),    // 5: pay.pb.PayCode
}
var file_pay_proto_depIdxs = []int32{
	1, // 0: pay.pb.PayCodeReq.platform:type_name -> pay.pb.PayPlatform
	3, // 1: pay.pb.PayCodeRes.resp:type_name -> pay.pb.Resp
	5, // 2: pay.pb.PayCodeRes.data:type_name -> pay.pb.PayCode
	0, // 3: pay.pb.PayCode.status:type_name -> pay.pb.PayStatus
	2, // 4: pay.pb.Pay.GetPayCode:input_type -> pay.pb.PayCodeReq
	4, // 5: pay.pb.Pay.GetPayCode:output_type -> pay.pb.PayCodeRes
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pay_proto_init() }
func file_pay_proto_init() {
	if File_pay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pay_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PayCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PayCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PayCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pay_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pay_proto_goTypes,
		DependencyIndexes: file_pay_proto_depIdxs,
		EnumInfos:         file_pay_proto_enumTypes,
		MessageInfos:      file_pay_proto_msgTypes,
	}.Build()
	File_pay_proto = out.File
	file_pay_proto_rawDesc = nil
	file_pay_proto_goTypes = nil
	file_pay_proto_depIdxs = nil
}
